# Generated by Django 4.1.7 on 2023-05-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65, verbose_name='Apelido do Caixa')),
                ('valor', models.FloatField(verbose_name='Valor de Abertura')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da Devolução')),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado')], max_length=1, verbose_name='Status')),
            ],
        ),
    ]
